INSERT INTO albums (id, album, artist, year, number) VALUES ('1', 'Sqt. Peppers Lonely Hearts Club Band', 'The Beatles', '1967', '1');
INSERT INTO albums (id, album, artist, year, number) VALUES ('2', 'Pet Sounds', 'The Beach Boys', '1966', '2');
INSERT INTO albums (id, album, artist, year, number) VALUES ('3', 'Revolver', 'The Beatles', '1966', '3');
INSERT INTO albums (id, album, artist, year, number) VALUES ('4', 'Highway 61', 'Bob Dylan', '1965', '4');
INSERT INTO albums (id, album, artist, year, number) VALUES ('5', 'Rubber Soul', 'The Beatles', '1965', '5');
INSERT INTO albums (id, album, artist, year, number) VALUES ('6', 'Whats Going On', 'Marvin Gaye', '1971', '6');
INSERT INTO albums (id, album, artist, year, number) VALUES ('7', 'Exile On Main Street', 'The Rolling Stones', '1972', '7');
INSERT INTO albums (id, album, artist, year, number) VALUES ('8', 'London Calling', 'The Clash', '1979', '8');
INSERT INTO albums (id, album, artist, year, number) VALUES ('9', 'Blonde On Blonde', 'Bob Dylan', '1966', '9');
INSERT INTO albums (id, album, artist, year, number) VALUES ('10', 'The White Album', 'The Beatles', '1968', '10');