/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://7c5hyt5oobbqjewsy5ldpkkibi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3ivsphhhhrhybordhcibvenvpm",
    "aws_cognito_identity_pool_id": "eu-west-1:71c5231c-7a27-4f06-9373-6936970dfe6f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_JDB2bUgre",
    "aws_user_pools_web_client_id": "1h1l2iin67e299bupt4thgmjf9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "notjustfriends-storage-6ebbad18182147-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
